---
title: "Event Plotting - AQUACAT"
author: "UKCEH; Adam Griffin"
date: "05/03/2020; updated 10/03/2020"
output: html_document
---
This report illustrates examples of widespread exceedences extracted from a 
30-year run of Grid-to-Grid (G2G), using `02_Event_Extract.py`.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ncdf4)
library(fields)
library(here)
library(readr)
```

# Data
```{r data}
print(getwd())
print(here::here())

events_per_year <- 5
nonexceed <- 1 - (events_per_year/365)

inun_thresh <- 0.01

ncname_lin <-"/prj/ResilRiskInds/hmfg2g_runs/baseline_qx_setting/dmflow_out.nc"
ncname_win <- "K:/hmfg2g_runs/baseline_qx_setting/dmflow_out.nc"  
# This file is ~36GB on the linux server.

if(substr(osVersion,1,3)=="Win"){
  ncname <- ncname_win
}else{
  ncname <- ncname_lin
}
ncin <- nc_open(ncname, readunlim=FALSE)
```

```{r, fig.height=8.25, fig.width=6, fig.align='center'}
plot_wide <- ncvar_get(ncin, "dmflow",
                    start=c(1,1,1000), count=c(-1, -1, 1))

brks <- c(-1.01, seq(0, max(plot_wide, na.rm=T), length.out=21))
image.plot(plot_wide, x=0:700, y=0:1250, xlim=c(0,700), ylim=c(1250,0),
           xlab="day 1000", asp=1, col=c("grey90", heat.colors(20)), 
           breaks=brks)

filepath <- paste0("/Scoping/InterimData/extremedates_",
                   floor(inun_thresh*100), "inun_", events_per_year, "epy.csv")

extremes <- read_csv(here::here(filepath), col_names=TRUE)

filepath <- paste0("/Scoping/InterimData/qPOT_", events_per_year,
                   "epy_sans_mask.csv")
invisible(qPOT5 <- unname(as.matrix(read_csv(here::here(filepath),
                                             col_names=TRUE, na="NA"))))

brks <- c(-1.01,seq(0, 800, length.out=21))
image.plot(t(qPOT5), x=0:700, y=0:1250, ylim=c(1250,0), xlim=c(0,700),
           xlab="qPOT5", asp=1, col=c("grey90", heat.colors(20)), breaks=brks)
```

## Examples of exceedence events
Here we see a small exceedence event (200 inundated cells), a medium exceedence event (~800 inundated events) and a high exceedence event (~12000 cells)
```{r examples, fig.height=8.25, fig.width=6, fig.align='center'}
Wmin <- which(extremes$Inun == min(extremes$Inun))
w <- extremes$Day[Wmin[1]]
flow <- ncvar_get(ncin, "dmflow", start=c(1,1,w), count=c(-1, -1, 1))
flow2 <- flow

WW <- which(as.matrix(flow) <= t(as.matrix(qPOT5)), arr.ind=T)
flow2 <- as.matrix(flow)

for(i in 1:nrow(WW)){
  if(is.na(flow2[WW[i,1], WW[i,2]])) next
  if(!(flow2[WW[i,1], WW[i,2]] == -1)){
    flow2[WW[i,1], WW[i,2]] <- -0.5
  }
}
brks <- c(-1.01, -0.51, seq(0, max(flow2, na.rm=T), length.out=20))

  image.plot(flow2, x=0:700, y=0:1250, ylim=c(1250,0),
             col=c("grey90", "grey70", heat.colors(19)), breaks=brks, asp=1)



Wmax <- which(extremes$Inun == max(extremes$Inun))
w <- extremes$Day[Wmax[1]]
flow <- ncvar_get(ncin, "dmflow", start=c(1,1,w), count=c(-1, -1, 1))
flow2 <- flow

WW <- which(as.matrix(flow) <= t(as.matrix(qPOT5)), arr.ind=T)
flow3 <- as.matrix(flow)

for(i in 1:nrow(WW)){
  if(is.na(flow3[WW[i,1], WW[i,2]])) next
  if(!(flow3[WW[i,1], WW[i,2]] == -1)){
    flow3[WW[i,1], WW[i,2]] <- -0.5
  }
}
brks <- c(-1.01, -0.51, seq(0, max(flow3, na.rm=T), length.out=20))

image.plot(flow3, x=0:700, y=0:1250, ylim=c(1250,0),
           col=c("grey90", "grey70", heat.colors(19)), breaks=brks, asp=1)



median(extremes$Inun) # between 808 and 810
Wmed <- which(extremes$Inun == 810)
w <- extremes$Day[Wmed[1]]
flow <- ncvar_get(ncin, "dmflow", start=c(1,1,w), count=c(-1, -1, 1))
flow2 <- flow

WW <- which(as.matrix(flow) <= t(as.matrix(qPOT5)), arr.ind=T)
flow4 <- as.matrix(flow)

for(i in 1:nrow(WW)){
  if(is.na(flow4[WW[i,1], WW[i,2]])) next
  if(!(flow4[WW[i,1], WW[i,2]] == -1)){
    flow4[WW[i,1], WW[i,2]] <- -0.5
  }
}
brks <- c(-1.01, -0.51, seq(0, max(flow4, na.rm=T), length.out=20))

image.plot(flow4, x=0:700, y=0:1250, ylim=c(1250,0),
           col=c("grey90", "grey70", heat.colors(19)), breaks=brks, asp=1)


nc_close(ncin)
```


```{r pdfs, echo=FALSE, results='hide'}
brks <- c(-1.01, -0.51, seq(0, max(flow2, na.rm=T), length.out=20))
pdf("qPOT5.pdf", width=8, height=11, pointsize=11)
  image.plot(t(qPOT5), x=0:700, y=0:1250, ylim=c(1250,0), xlim=c(0,700),
           xlab="qPOT5", asp=1, col=c("grey90", heat.colors(20)), breaks=brks)
dev.off()

pdf("eventmin.pdf", width=8, height=11, pointsize=10)
par(mar=c(3,3,1,1), mgp=c(2,1,0))
  image.plot(flow2, x=0:700, y=0:1250, ylim=c(1250,0),
             col=c("grey90", "grey70", heat.colors(19)), breaks=brks, asp=1)
dev.off()

brks <- c(-1.01, -0.51, seq(0, max(flow3, na.rm=T), length.out=20))
pdf("eventmax.pdf", width=8, height=11, pointsize=10)
  par(mar=c(3,3,1,1), mgp=c(2,1,0))
  image.plot(flow3, x=0:700, y=0:1250, ylim=c(1250,0),
             col=c("grey90", "grey70", heat.colors(19)), breaks=brks, asp=1)
dev.off()

brks <- c(-1.01, -0.51, seq(0, max(flow4, na.rm=T), length.out=20))
pdf("eventmed.pdf", width=8, height=11, pointsize=10)
  par(mar=c(3,3,1,1), mgp=c(2,1,0))
  image.plot(flow4, x=0:700, y=0:1250, ylim=c(1250,0),
             col=c("grey90", "grey70", heat.colors(19)), breaks=brks, asp=1)
dev.off()
```